id = "golangci-lint"
name = "Golangci-Lint"
description = "Golangci Lint support."
version = "0.1.0"
schema_version = 1
authors = ["Jordan Gregory <jordan@j4ng5y.dev>"]
repository = "https://github.com/j4ng5y/zed_golangci_lint"

[language_servers.golangci-lint]
name = "golangci-lint"
language = "Golangci Lint"
languages = ["Go"]
